Fixed issue with multiple definition of fileExists function in IOobject.h. Issue with undefined reference to function template arises - need to be fixed.